version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    command: --nojournal
    ports:
        - "27017:27017"
    networks:
      - server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./storage:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    networks:
      - server
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-container:27017/

networks:
  server:
    driver: bridge