version: '3.8'
services:
  geo:
    image: panandafog/geo
    container_name: geo-container
    restart: always
    ports:
        - "8080:8080"
    networks:
      - server
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    ports:
        - "27017:27017"
    networks:
      - server
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: geo_db
    volumes:
      - ./mongodb-data:/data/db
      - ./mongodb-log:/var/log/mongodb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command:
      - '--logpath'
      - '/var/log/mongodb/mongodb.log'

networks:
  server:
    driver: bridge
